# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 180, 160, 83))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.audioMenu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.audioMenu.setObjectName("audioMenu")
        self.verticalLayout.addWidget(self.audioMenu)
        self.citraMenu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.citraMenu.setObjectName("citraMenu")
        self.verticalLayout.addWidget(self.citraMenu)
        self.videoMenu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.videoMenu.setObjectName("videoMenu")
        self.verticalLayout.addWidget(self.videoMenu)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 50, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menuLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.menuLabel.setObjectName("menuLabel")
        self.verticalLayout_2.addWidget(self.menuLabel)
        self.menuLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.menuLabel_2.setObjectName("menuLabel_2")
        self.verticalLayout_2.addWidget(self.menuLabel_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.audioMenu.setText(_translate("MainWindow", "Audio"))
        self.citraMenu.setText(_translate("MainWindow", "Citra"))
        self.videoMenu.setText(_translate("MainWindow", "Video"))
        self.menuLabel.setText(_translate("MainWindow", "Welcome to StegoApp"))
        self.menuLabel_2.setText(_translate("MainWindow", "Main Menu"))
